name: ci
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Tests
        run: deno task test
